exports.dispositivoModel = (device) => ({
    IDDispositivo:                  device.IDDispositivo,
    IDSubsistema:                   device.IDSubsistema,
    IDTipoFamilia:                  device.IDTipoFamilia,
    IDFamilia:                      device.IDFamilia,
    IDFabricante:                   device.IDFabricante,
    IDTipoDispositivo:              device.IDTipoDispositivo,
    IDGateway:                      device.IDGateway,
    IDControlador:                  device.IDControlador,
    IDModelo:                       device.IDModelo,
    IDEdificio:                     device.IDEdificio,
    IDZona:                         device.IDZona,
    IDPuerta:                       device.IDPuerta,
    NombreDispositivo :             device.NombreDispositivo,
    Descripcion:                    device.Descripcion,
    IDIconografia:                  device.IDIconografia,
    IDMenuPropio:                   device.IDMenuPropio,
    Estatus :                       device.Estatus,
    Sentidos :                      device.Sentidos,
    Ignorado:                       device.Ignorado,
    Enrolamiento:                   device.Enrolamiento,
    Latitud:                        device.Latitud,
    Longitud:                       device.Longitud,
    DireccionGPS:                   device.DireccionGPS,
    GeometriaGPS:                   device.GeometriaGPS,
    IDTipoEvento:                   device.IDTipoEvento,
    IDModeloElemento:               device.IDModeloElemento,
    FechaCreacion:                  device.FechaCreacion,
    FechaDesactivacion:             device.FechaDesactivacion,
    FechaEliminacion:               device.FechaEliminacion,
    Parametros:                     device.Parametros,
    Certificado:                    device.Certificado,
    PuertoSSL:                      device.PuertoSSL,
    PuertoNoSSL:                    device.PuertoNoSSL,
    PuertoMantenimiento:            device.PuertoMantenimiento,
    PuertoConexionSC:               device.PuertoConexionSC,
    PuertoConexionCC:               device.PuertoConexionCC,
    SOAP:                           device.SOAP,
    Socket:                         device.Socket,
    API:                            device.API,
    Sincroniza:                     device.Sincroniza,
    DireccionAIPV4:                 device.DireccionAIPV4,
    DireccionBIPv4:                 device.DireccionBIPv4,
    DireccionAIPV6:                 device.DireccionAIPV6,
    DireccionBIPv6:                 device.DireccionBIPv6,
    DireccionPublica1:              device.DireccionPublica1,
    DireccionPublica2:              device.DireccionPublica2,
    Serial:                         device.Serial,
    user:                           device.user,
    password:                       device.password,
    IDManual:                       device.IDManual,
    Directo:                        device.Directo    
});